### PR TITLE
Add a tmeRepositoryConfig struct and a tmeRepositoryConfig initialisa…

### PR DESCRIPTION
**Pull request by dawngerpony**
…tion function that uses it, to avoid any more problems with broken interfaces that some dependent applications were suffering.

```
$ go test
PASS
ok      github.com/Financial-Times/tme-reader/tmereader 0.019s
```

Hey folks, can you have a look at this small PR?

FYI this is currently breaking [v1-orgs-transformer](https://github.com/Financial-Times/v1-orgs-transformer), so I'll fix that library via a PR once this change is in `master`.

### CODE REVIEW

**Comment by duffj** [comment]
hey folks, can you have a look at this small PR?

**Comment by dawngerpony** [comment]
FYI I'm just updating the README to use the new function in its example.

**Comment by izzyblues** [comment]
+1

**Comment by tosan88** [comment]
lgtm

**Pull request merged**
